// The lessons themselves. Wording drafted by Claude and approved on 2026-10-06 (Khaya replied "Approved" to the draft in the
// Claude Doc "Growfit coach lessons: first batch"). A lesson with `approved: false` is
// invisible everywhere (see lib/lessons.ts). Edit the wording here, in a pull request.

import type { Lesson } from "@/lib/lessons";

export const LESSONS: readonly Lesson[] = [
  {
    slug: "playing-out-from-the-back",
    area: "tactical",
    title: "Playing out from the back",
    summary: "Why short passes from the back get lost, and how to give the player on the ball a way out.",
    problemKeys: ["ip-lose-playing-out"],
    body: [
      "What you see: The keeper or defenders pass short and the other team wins the ball near your goal.",
      "Why it happens: The player on the ball has no safe pass, because teammates stand behind the opponents or too close together. Or the pass is rushed because the player has not looked first.",
      "What to try: Play 4 v 2 in a small grid so the player on the ball always has two ways out. Teach \"look before you receive\": check over your shoulder, then take the ball on your back foot. Give the full-backs permission to go wide and the keeper permission to kick long when there is no safe pass.",
      "Watch for next match: Does the player on the ball have a pass on, or are they forced?",
    ],
    approved: true,
  },
  {
    slug: "too-many-long-balls",
    area: "tactical",
    title: "Too many long balls",
    summary: "Why the long ball keeps coming back, and how to build trust in the short pass.",
    problemKeys: ["ip-long-balls"],
    body: [
      "What you see: The ball is kicked forward from everywhere and comes straight back.",
      "Why it happens: Players do not trust the short pass, or nobody is close enough to receive one. Long balls feel safe because they take the ball away from your goal.",
      "What to try: Set a rule in a practice game: three passes before any long ball. Praise the brave short pass even when it goes wrong.",
      "Watch for next match: Are there teammates within a short pass when the long ball is kicked?",
    ],
    approved: true,
  },
  {
    slug: "spreading-out",
    area: "tactical",
    title: "Spreading out to give the ball carrier a pass",
    summary: "How to get children to use the whole pitch instead of crowding the ball.",
    problemKeys: ["ip-no-width"],
    body: [
      "What you see: Everyone is bunched on one side and the player with the ball is surrounded.",
      "Why it happens: Children chase the ball. They do not yet see the whole pitch.",
      "What to try: Mark width with cones near the touchlines. Play a game where a goal only counts if a wide player touched the ball first. Younger children: \"stand on the chalk\".",
      "Watch for next match: Is there a player near each touchline when you attack?",
    ],
    approved: true,
  },
  {
    slug: "taking-the-shot",
    area: "technical",
    title: "Taking the shot in the box",
    summary: "Why children pass up shots in the box, and how to make shooting welcome.",
    problemKeys: ["ip-no-shot"],
    body: [
      "What you see: Players dribble or pass sideways in the box and the chance is gone.",
      "Why it happens: Fear of missing, or wanting to pass to a friend. Sometimes they simply have not been told shooting is welcome.",
      "What to try: Finishing games with many shots and no blame for misses. Celebrate the shot, not only the goal. Ask: \"What did you see before you decided?\"",
      "Watch for next match: Count the shots, not only the goals.",
    ],
    approved: true,
  },
  {
    slug: "breaking-a-deep-block",
    area: "tactical",
    title: "Breaking a team that sits deep",
    summary: "For U13 and U15: how to make space against a team that keeps everyone behind the ball.",
    problemKeys: ["ip-deep-block"],
    body: [
      "What you see: The other team keeps everyone behind the ball and you keep passing in front of them.",
      "Why it happens: There is no space behind them, so you need movement and patience to make some.",
      "What to try: Practise switching the ball quickly side to side so defenders have to shift. Add a runner who moves between two defenders. Shots from the edge of the box make deep teams come out.",
      "Watch for next match: Does your team keep moving the ball, or stop and wait?",
    ],
    approved: true,
  },
  {
    slug: "bunching-around-the-ball",
    area: "tactical",
    title: "Bunching around the ball",
    summary: "How to stop five or six players chasing the ball and leaving the rest of the pitch empty.",
    problemKeys: ["oop-bunching"],
    body: [
      "What you see: Five or six of your players surround the ball while the rest of the pitch is empty.",
      "Why it happens: Everyone wants to help, so everyone goes to the ball.",
      "What to try: Give each player a zone and a job: one pressures, one covers behind, the rest hold their line. Play a small game where only two players may go to the ball.",
      "Watch for next match: When the other team switches play, is anyone free?",
    ],
    approved: true,
  },
  {
    slug: "pressuring-the-ball",
    area: "tactical",
    title: "Pressuring the player with the ball",
    summary: "How to make sure someone always goes to the ball carrier.",
    problemKeys: ["oop-no-pressure"],
    body: [
      "What you see: The other team's player dribbles forward with no one close to them.",
      "Why it happens: Each player thinks someone else will go. Nobody owns the decision.",
      "What to try: Teach \"nearest player goes\". Practise 1 v 1 defending: approach fast, then slow down and stay low. Call a name, not \"someone\".",
      "Watch for next match: Who goes to the ball first when it is won by the other team?",
    ],
    approved: true,
  },
  {
    slug: "staying-connected-between-the-lines",
    area: "tactical",
    title: "Staying connected between the lines",
    summary: "How to keep defenders, midfielders and forwards close enough to support each other.",
    problemKeys: ["oop-far-apart"],
    body: [
      "What you see: There is a big gap between defenders, midfielders and forwards.",
      "Why it happens: Some players stay back for safety, others push up. Nobody keeps the team connected.",
      "What to try: Practise moving as a unit: when the ball goes forward, everyone steps up together. Use a rope or bibs held between three players to show the right distance.",
      "Watch for next match: Can a pass travel through your team without a gap?",
    ],
    approved: true,
  },
  {
    slug: "pressing-together",
    area: "tactical",
    title: "Pressing together",
    summary: "For U13 and U15: how to agree when the team presses so the press does not break.",
    problemKeys: ["oop-press-timing"],
    body: [
      "What you see: One player runs at the ball and the others stay put.",
      "Why it happens: There is no agreed signal for when to press.",
      "What to try: Agree a trigger, for example a backward pass or a poor touch. Everyone presses together on the trigger, or no one does. Practise it in a small grid with a rest between rounds.",
      "Watch for next match: Does everyone start pressing at the same moment?",
    ],
    approved: true,
  },
  {
    slug: "defending-the-back-post",
    area: "tactical",
    title: "Defending the back post",
    summary: "For U13 and U15: how to stop runners getting free at the far post.",
    problemKeys: ["oop-back-post"],
    body: [
      "What you see: The other team scores from a cross at the far post.",
      "Why it happens: Players watch the ball and forget the runner behind them.",
      "What to try: Teach \"see the ball and your player\". Practise defending crosses with two attackers and two defenders. Name who marks the back post before every corner and cross.",
      "Watch for next match: Does anyone check behind them before the cross?",
    ],
    approved: true,
  },
  {
    slug: "keeping-the-ball-when-you-win-it",
    area: "tactical",
    title: "Keeping the ball when you win it",
    summary: "How to stay calm in the moment after winning the ball.",
    problemKeys: ["at-kick-away"],
    body: [
      "What you see: The ball is won and immediately booted forward or out.",
      "Why it happens: The moment after winning the ball feels dangerous.",
      "What to try: Practise the first pass after winning it: look up and play to a free teammate. Praise the calm touch.",
      "Watch for next match: What is the first thing your team does when it wins the ball?",
    ],
    approved: true,
  },
  {
    slug: "supporting-the-player-who-wins-it",
    area: "tactical",
    title: "Supporting the player who wins the ball",
    summary: "How to get teammates running forward the moment the ball is won.",
    problemKeys: ["at-no-support"],
    body: [
      "What you see: One player wins the ball and is alone.",
      "Why it happens: The rest of the team is still in defensive mode.",
      "What to try: Teach \"win it, run\": the two nearest teammates move into space at once. Play a transition game where winning the ball means three players go.",
      "Watch for next match: How many teammates are within a pass when the ball is won?",
    ],
    approved: true,
  },
  {
    slug: "using-the-space-when-they-lose-it",
    area: "tactical",
    title: "Using the space when the other team loses the ball",
    summary: "For U13 and U15: how to punish a team that is out of position.",
    problemKeys: ["at-use-space"],
    body: [
      "What you see: The other team loses the ball with players out of position and your team is slow to punish it.",
      "Why it happens: Players do not scan for open space in the first seconds.",
      "What to try: Practise a quick forward pass in the first three seconds. Ask: \"Where was the space? Who saw it?\"",
      "Watch for next match: Is there a pass forward in the first three seconds after winning it?",
    ],
    approved: true,
  },
  {
    slug: "chasing-after-you-lose-it",
    area: "psychological",
    title: "Chasing after you lose the ball",
    summary: "How to get players working to win the ball back instead of standing and watching.",
    problemKeys: ["dt-watch"],
    body: [
      "What you see: The ball is lost and players stand still.",
      "Why it happens: Disappointment, or they think it is someone else's job.",
      "What to try: Teach the \"five-second chase\": everyone near the ball tries to win it back for five seconds. Make it a game with a prize for winning it back.",
      "Watch for next match: What do players do in the first moments after losing it?",
    ],
    approved: true,
  },
  {
    slug: "getting-back-behind-the-ball",
    area: "tactical",
    title: "Getting back behind the ball",
    summary: "How to help players know where to run when the ball is lost.",
    problemKeys: ["dt-slow-recovery"],
    body: [
      "What you see: The other team breaks while your players are still up the pitch.",
      "Why it happens: Players do not know where to run back to.",
      "What to try: Practise \"get goal-side\": run back between the ball and your goal. Use cones to mark a recovery line.",
      "Watch for next match: How long until your team is back behind the ball?",
    ],
    approved: true,
  },
  {
    slug: "stopping-the-counter-attack",
    area: "tactical",
    title: "Stopping the counter-attack",
    summary: "For U13 and U15: how to slow the other team's break in the first seconds.",
    problemKeys: ["dt-counter"],
    body: [
      "What you see: You lose the ball and they are through before you react.",
      "Why it happens: Too many players are ahead of the ball and the nearest ones do not delay.",
      "What to try: Teach the nearest player to slow the ball carrier and not dive in, so teammates can recover. Keep one or two players back when you attack.",
      "Watch for next match: Who is the nearest player when the ball is lost, and what do they do?",
    ],
    approved: true,
  },
  {
    slug: "marking-at-corners",
    area: "tactical",
    title: "Marking at corners",
    summary: "How to agree who marks whom before the corner is taken.",
    problemKeys: ["sp-marking"],
    body: [
      "What you see: Attackers are free in the box.",
      "Why it happens: Marking was never agreed.",
      "What to try: Write the marking down before the match and tell each child their player. Practise corners in training with a simple plan.",
      "Watch for next match: Does each defender know their player before the corner?",
    ],
    approved: true,
  },
  {
    slug: "our-own-corners-and-free-kicks",
    area: "tactical",
    title: "Making use of our own corners and free kicks",
    summary: "How to give your own set pieces a simple plan.",
    problemKeys: ["sp-waste-own"],
    body: [
      "What you see: The ball goes to the first defender or out.",
      "Why it happens: No plan for where the ball goes.",
      "What to try: Agree one or two simple routines, like a short corner or a near-post run. Practise them often.",
      "Watch for next match: Does the set piece end with a shot or a pass?",
    ],
    approved: true,
  },
  {
    slug: "keeping-the-ball-from-throw-ins",
    area: "technical",
    title: "Keeping the ball from throw-ins",
    summary: "How to give the thrower two good options.",
    problemKeys: ["sp-throw-ins"],
    body: [
      "What you see: The thrower has nobody to throw to, or the receiver is marked.",
      "Why it happens: Players stand still waiting for the throw.",
      "What to try: Teach two players to move: one close, one a bit further. The thrower looks first, then throws. Practise throw-ins in a game.",
      "Watch for next match: Does the thrower have two options?",
    ],
    approved: true,
  },
  {
    slug: "second-balls-after-set-pieces",
    area: "tactical",
    title: "Second balls after set pieces",
    summary: "For U13 and U15: how to stay switched on after the first clearance.",
    problemKeys: ["sp-second-balls"],
    body: [
      "What you see: The first ball is cleared but the ball drops and they score.",
      "Why it happens: The team relaxes after the first contact.",
      "What to try: Place two players just outside the box to win the second ball. Practise reacting after a clearance.",
      "Watch for next match: Who is outside the box after the first contact?",
    ],
    approved: true,
  },
];
