// The lessons themselves. Wording drafted by Claude and approved on 2026-10-06 (Khaya replied "Approved" to the
// draft in the Claude Doc "Growfit coach lessons: first batch"). Edit the wording here, in a pull request.
// Each row is one lesson; `toLesson` gives it the four fixed parts. A lesson with `approved: false` is
// invisible everywhere (see lib/lessons.ts).

import type { Lesson, LessonAreaKey } from "@/lib/lessons";

type Row = readonly [
  problemKey: string, slug: string, area: LessonAreaKey, title: string, summary: string,
  see: string, why: string, tryThis: string, watch: string,
];

const ROWS: readonly Row[] = [
  [
    "ip-lose-playing-out",
    "playing-out-from-the-back",
    "tactical",
    "Playing out from the back",
    "Why short passes from the back get lost, and how to give the player on the ball a way out.",
    "The keeper or defenders pass short and the other team wins the ball near your goal.",
    "The player on the ball has no safe pass, because teammates stand behind the opponents or too close together. Or the pass is rushed because the player has not looked first.",
    "Play 4 v 2 in a small grid so the player on the ball always has two ways out. Teach \"look before you receive\": check over your shoulder, then take the ball on your back foot. Give the full-backs permission to go wide and the keeper permission to kick long when there is no safe pass.",
    "Does the player on the ball have a pass on, or are they forced?",
  ],
  [
    "ip-long-balls",
    "too-many-long-balls",
    "tactical",
    "Too many long balls",
    "Why the long ball keeps coming back, and how to build trust in the short pass.",
    "The ball is kicked forward from everywhere and comes straight back.",
    "Players do not trust the short pass, or nobody is close enough to receive one. Long balls feel safe because they take the ball away from your goal.",
    "Set a rule in a practice game: three passes before any long ball. Praise the brave short pass even when it goes wrong.",
    "Are there teammates within a short pass when the long ball is kicked?",
  ],
  [
    "ip-no-width",
    "spreading-out",
    "tactical",
    "Spreading out to give the ball carrier a pass",
    "How to get children to use the whole pitch instead of crowding the ball.",
    "Everyone is bunched on one side and the player with the ball is surrounded.",
    "Children chase the ball. They do not yet see the whole pitch.",
    "Mark width with cones near the touchlines. Play a game where a goal only counts if a wide player touched the ball first. Younger children: \"stand on the chalk\".",
    "Is there a player near each touchline when you attack?",
  ],
  [
    "ip-no-shot",
    "taking-the-shot",
    "technical",
    "Taking the shot in the box",
    "Why children pass up shots in the box, and how to make shooting welcome.",
    "Players dribble or pass sideways in the box and the chance is gone.",
    "Fear of missing, or wanting to pass to a friend. Sometimes they simply have not been told shooting is welcome.",
    "Finishing games with many shots and no blame for misses. Celebrate the shot, not only the goal. Ask: \"What did you see before you decided?\"",
    "Count the shots, not only the goals.",
  ],
  [
    "ip-deep-block",
    "breaking-a-deep-block",
    "tactical",
    "Breaking a team that sits deep",
    "For U13 and U15: how to make space against a team that keeps everyone behind the ball.",
    "The other team keeps everyone behind the ball and you keep passing in front of them.",
    "There is no space behind them, so you need movement and patience to make some.",
    "Practise switching the ball quickly side to side so defenders have to shift. Add a runner who moves between two defenders. Shots from the edge of the box make deep teams come out.",
    "Does your team keep moving the ball, or stop and wait?",
  ],
  [
    "oop-bunching",
    "bunching-around-the-ball",
    "tactical",
    "Bunching around the ball",
    "How to stop five or six players chasing the ball and leaving the rest of the pitch empty.",
    "Five or six of your players surround the ball while the rest of the pitch is empty.",
    "Everyone wants to help, so everyone goes to the ball.",
    "Give each player a zone and a job: one pressures, one covers behind, the rest hold their line. Play a small game where only two players may go to the ball.",
    "When the other team switches play, is anyone free?",
  ],
  [
    "oop-no-pressure",
    "pressuring-the-ball",
    "tactical",
    "Pressuring the player with the ball",
    "How to make sure someone always goes to the ball carrier.",
    "The other team's player dribbles forward with no one close to them.",
    "Each player thinks someone else will go. Nobody owns the decision.",
    "Teach \"nearest player goes\". Practise 1 v 1 defending: approach fast, then slow down and stay low. Call a name, not \"someone\".",
    "Who goes to the ball first when it is won by the other team?",
  ],
  [
    "oop-far-apart",
    "staying-connected-between-the-lines",
    "tactical",
    "Staying connected between the lines",
    "How to keep defenders, midfielders and forwards close enough to support each other.",
    "There is a big gap between defenders, midfielders and forwards.",
    "Some players stay back for safety, others push up. Nobody keeps the team connected.",
    "Practise moving as a unit: when the ball goes forward, everyone steps up together. Use a rope or bibs held between three players to show the right distance.",
    "Can a pass travel through your team without a gap?",
  ],
  [
    "oop-press-timing",
    "pressing-together",
    "tactical",
    "Pressing together",
    "For U13 and U15: how to agree when the team presses so the press does not break.",
    "One player runs at the ball and the others stay put.",
    "There is no agreed signal for when to press.",
    "Agree a trigger, for example a backward pass or a poor touch. Everyone presses together on the trigger, or no one does. Practise it in a small grid with a rest between rounds.",
    "Does everyone start pressing at the same moment?",
  ],
  [
    "oop-back-post",
    "defending-the-back-post",
    "tactical",
    "Defending the back post",
    "For U13 and U15: how to stop runners getting free at the far post.",
    "The other team scores from a cross at the far post.",
    "Players watch the ball and forget the runner behind them.",
    "Teach \"see the ball and your player\". Practise defending crosses with two attackers and two defenders. Name who marks the back post before every corner and cross.",
    "Does anyone check behind them before the cross?",
  ],
  [
    "at-kick-away",
    "keeping-the-ball-when-you-win-it",
    "tactical",
    "Keeping the ball when you win it",
    "How to stay calm in the moment after winning the ball.",
    "The ball is won and immediately booted forward or out.",
    "The moment after winning the ball feels dangerous.",
    "Practise the first pass after winning it: look up and play to a free teammate. Praise the calm touch.",
    "What is the first thing your team does when it wins the ball?",
  ],
  [
    "at-no-support",
    "supporting-the-player-who-wins-it",
    "tactical",
    "Supporting the player who wins the ball",
    "How to get teammates running forward the moment the ball is won.",
    "One player wins the ball and is alone.",
    "The rest of the team is still in defensive mode.",
    "Teach \"win it, run\": the two nearest teammates move into space at once. Play a transition game where winning the ball means three players go.",
    "How many teammates are within a pass when the ball is won?",
  ],
  [
    "at-use-space",
    "using-the-space-when-they-lose-it",
    "tactical",
    "Using the space when the other team loses the ball",
    "For U13 and U15: how to punish a team that is out of position.",
    "The other team loses the ball with players out of position and your team is slow to punish it.",
    "Players do not scan for open space in the first seconds.",
    "Practise a quick forward pass in the first three seconds. Ask: \"Where was the space? Who saw it?\"",
    "Is there a pass forward in the first three seconds after winning it?",
  ],
  [
    "dt-watch",
    "chasing-after-you-lose-it",
    "psychological",
    "Chasing after you lose the ball",
    "How to get players working to win the ball back instead of standing and watching.",
    "The ball is lost and players stand still.",
    "Disappointment, or they think it is someone else's job.",
    "Teach the \"five-second chase\": everyone near the ball tries to win it back for five seconds. Make it a game with a prize for winning it back.",
    "What do players do in the first moments after losing it?",
  ],
  [
    "dt-slow-recovery",
    "getting-back-behind-the-ball",
    "tactical",
    "Getting back behind the ball",
    "How to help players know where to run when the ball is lost.",
    "The other team breaks while your players are still up the pitch.",
    "Players do not know where to run back to.",
    "Practise \"get goal-side\": run back between the ball and your goal. Use cones to mark a recovery line.",
    "How long until your team is back behind the ball?",
  ],
  [
    "dt-counter",
    "stopping-the-counter-attack",
    "tactical",
    "Stopping the counter-attack",
    "For U13 and U15: how to slow the other team's break in the first seconds.",
    "You lose the ball and they are through before you react.",
    "Too many players are ahead of the ball and the nearest ones do not delay.",
    "Teach the nearest player to slow the ball carrier and not dive in, so teammates can recover. Keep one or two players back when you attack.",
    "Who is the nearest player when the ball is lost, and what do they do?",
  ],
  [
    "sp-marking",
    "marking-at-corners",
    "tactical",
    "Marking at corners",
    "How to agree who marks whom before the corner is taken.",
    "Attackers are free in the box.",
    "Marking was never agreed.",
    "Write the marking down before the match and tell each child their player. Practise corners in training with a simple plan.",
    "Does each defender know their player before the corner?",
  ],
  [
    "sp-waste-own",
    "our-own-corners-and-free-kicks",
    "tactical",
    "Making use of our own corners and free kicks",
    "How to give your own set pieces a simple plan.",
    "The ball goes to the first defender or out.",
    "No plan for where the ball goes.",
    "Agree one or two simple routines, like a short corner or a near-post run. Practise them often.",
    "Does the set piece end with a shot or a pass?",
  ],
  [
    "sp-throw-ins",
    "keeping-the-ball-from-throw-ins",
    "technical",
    "Keeping the ball from throw-ins",
    "How to give the thrower two good options.",
    "The thrower has nobody to throw to, or the receiver is marked.",
    "Players stand still waiting for the throw.",
    "Teach two players to move: one close, one a bit further. The thrower looks first, then throws. Practise throw-ins in a game.",
    "Does the thrower have two options?",
  ],
  [
    "sp-second-balls",
    "second-balls-after-set-pieces",
    "tactical",
    "Second balls after set pieces",
    "For U13 and U15: how to stay switched on after the first clearance.",
    "The first ball is cleared but the ball drops and they score.",
    "The team relaxes after the first contact.",
    "Place two players just outside the box to win the second ball. Practise reacting after a clearance.",
    "Who is outside the box after the first contact?",
  ],
];

function toLesson([problemKey, slug, area, title, summary, see, why, tryThis, watch]: Row): Lesson {
  return {
    slug, area, title, summary,
    problemKeys: [problemKey],
    body: [
      `What you see: ${see}`,
      `Why it happens: ${why}`,
      `What to try: ${tryThis}`,
      `Watch for next match: ${watch}`,
    ],
    approved: true,
  };
}

export const LESSONS: readonly Lesson[] = ROWS.map(toLesson);
